// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-apckH3lvVsMbKHMdg-cogjPB14NxXU',
    appId: '1:899604486643:web:669bd4dc8948a726c09a86',
    messagingSenderId: '899604486643',
    projectId: 'flash-chat-81c2a',
    authDomain: 'flash-chat-81c2a.firebaseapp.com',
    storageBucket: 'flash-chat-81c2a.appspot.com',
    measurementId: 'G-CVK4VLKWD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2SbRBHBXFEzZk9PDdAqHceAv35buIu4',
    appId: '1:899604486643:android:2d4ef53130eedea5c09a86',
    messagingSenderId: '899604486643',
    projectId: 'flash-chat-81c2a',
    storageBucket: 'flash-chat-81c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsXrHJzCPvs5DZULtwkf5xxUihzj17Ckw',
    appId: '1:899604486643:ios:212a5f2ccbe40630c09a86',
    messagingSenderId: '899604486643',
    projectId: 'flash-chat-81c2a',
    storageBucket: 'flash-chat-81c2a.appspot.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsXrHJzCPvs5DZULtwkf5xxUihzj17Ckw',
    appId: '1:899604486643:ios:8f653ff268f78432c09a86',
    messagingSenderId: '899604486643',
    projectId: 'flash-chat-81c2a',
    storageBucket: 'flash-chat-81c2a.appspot.com',
    iosBundleId: 'com.example.flashChatFlutter.RunnerTests',
  );
}
